name: Build & publish PyPI packages

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.**

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Build sdist package
        working-directory: ./python
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: "python/dist/*.tar.gz"

  build-win64-wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheel for python ${{ matrix.python-version }}
        working-directory: ./python
        run: |
          python -m pip install --upgrade pip build ninja
          python -m build --wheel
        env:
          CMAKE_GENERATOR: Ninja
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: "python/dist/*.whl"

  pypi-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build-sdist, build-win64-wheels]
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: packages
        path: python/dist
    - name: Test PyPI publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: python/dist
        skip-existing: true
    - name: PyPI publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: python/dist
